name: CICD

on: 
 workflow_dispatch:

jobs:

  code:
      runs-on: ubuntu-latest
      steps:
        - name: Code checkout
          run: echo "code clone from github"
          
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Build docker container
          run: echo "docker container build"
          
  test:
      runs-on: ubuntu-latest
      steps:
        - name: Test the container
          run: echo "testing the container"
          
  deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Deploy the app
          run: echo "docker compose deploy the app'
  
